---
- hosts: all
  become: yes
  vars:
    db_user: first_user
    db_pass: mebium123
    db_name: medium_db
  tasks: 
  - name:
    apt:
      name: php
      state: latest
  - name: install apache2
    apt:
      name: apache2
      state: latest
      update_cache: yes
  - name: Installing Mysql  and dependencies
    package:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - mysql-server
      - mysql-client 
      - python3-mysqldb
      - libmysqlclient-dev
    become: yes
  - name: start and enable mysql service
    service:
      name: mysql
      state: started
      enabled: yes
  - name: create mysql user (first_user)
    mysql_user:
       name: "{{db_user}}"
       password: "{{db_pass}}"
       priv: '*.*:ALL'
       host: '%'
       state: present
  - name: create  medium_db
    mysql_db:
      name: "{{db_name}}"
      state: present
  - name: Enable remote login to mysql
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '^bind-address'
      line: 'bind-address = 0.0.0.0'
      backup: yes
    notify:
       - Restart mysql
  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted


